### ISSUE TITLE
How to support Embeddables?

### ISSUE THREAD

**Issue by pbalan** [JonathanPrince/loopback-component-fixtures#28]
Hi,

### Bug Report

I am using `loopback-component-fixtures` library for a loopback component I am working on. Am using **memory** db.

## When I try a model with embeddables, I get the following error.

>
> **Note**: If I use "type": "Object", instead of "type": "ProductAttribute", it works fine.
>

### Stack Trace
```
Unhandled rejection ReferenceError: g is not defined
    at new ProductAttribute (eval at createModelClassCtor (/projects/component-commerce/node_modules/loopback-datasource-juggler/lib/model-builder.js:671:21), <anonymous>:10:27)
    at ProductAttribute (eval at createModelClassCtor (/projects/component-commerce/node_modules/loopback-datasource-juggler/lib/model-builder.js:671:21), <anonymous>:7:18)
    at ProductDetail.set [as attributes] (/projects/component-commerce/node_modules/loopback-datasource-juggler/lib/model-builder.js:598:81)
    at ProductDetail.ModelBaseClass._initProperties (/projects/component-commerce/node_modules/loopback-datasource-juggler/lib/model.js:202:17)
    at ProductDetail.ModelBaseClass (/projects/component-commerce/node_modules/loopback-datasource-juggler/lib/model.js:60:8)
    at ProductDetail.Model (eval at createModelClassCtor (/projects/component-commerce/node_modules/loopback-datasource-juggler/lib/model-builder.js:671:21), <anonymous>:12:24)
    at ProductDetail.PersistedModel (eval at createModelClassCtor (/projects/component-commerce/node_modules/loopback-datasource-juggler/lib/model-builder.js:671:21), <anonymous>:12:24)
    at new ProductDetail (eval at createModelClassCtor (/projects/component-commerce/node_modules/loopback-datasource-juggler/lib/model-builder.js:671:21), <anonymous>:12:24)
    at Function.DataAccessObject.create (/projects/component-commerce/node_modules/loopback-datasource-juggler/lib/dao.js:359:13)
    at Function.replaceOrCreate (/projects/component-commerce/node_modules/loopback-datasource-juggler/lib/dao.js:924:17)
    at Promise.map (/projects/component-commerce/common/models/Model.ProductDetail.js:16:30)
    at tryCatcher (/projects/component-commerce/node_modules/bluebird/js/release/util.js:16:23)
    at MappingPromiseArray._promiseFulfilled (/projects/component-commerce/node_modules/bluebird/js/release/map.js:61:38)
    at MappingPromiseArray.PromiseArray._iterate (/projects/component-commerce/node_modules/bluebird/js/release/promise_array.js:114:31)
    at MappingPromiseArray.init (/projects/component-commerce/node_modules/bluebird/js/release/promise_array.js:78:10)
    at MappingPromiseArray._asyncInit (/projects/component-commerce/node_modules/bluebird/js/release/map.js:30:10)

Unhandled rejection ReferenceError: g is not defined
    at new ProductAttribute (eval at createModelClassCtor (/projects/component-commerce/node_modules/loopback-datasource-juggler/lib/model-builder.js:671:21), <anonymous>:10:27)
    at ProductAttribute (eval at createModelClassCtor (/projects/component-commerce/node_modules/loopback-datasource-juggler/lib/model-builder.js:671:21), <anonymous>:7:18)
    at ProductDetail.set [as attributes] (/projects/component-commerce/node_modules/loopback-datasource-juggler/lib/model-builder.js:598:81)
    at ProductDetail.ModelBaseClass._initProperties (/projects/component-commerce/node_modules/loopback-datasource-juggler/lib/model.js:202:17)
    at ProductDetail.ModelBaseClass (/projects/component-commerce/node_modules/loopback-datasource-juggler/lib/model.js:60:8)
    at ProductDetail.Model (eval at createModelClassCtor (/projects/component-commerce/node_modules/loopback-datasource-juggler/lib/model-builder.js:671:21), <anonymous>:12:24)
    at ProductDetail.PersistedModel (eval at createModelClassCtor (/projects/component-commerce/node_modules/loopback-datasource-juggler/lib/model-builder.js:671:21), <anonymous>:12:24)
    at new ProductDetail (eval at createModelClassCtor (/projects/component-commerce/node_modules/loopback-datasource-juggler/lib/model-builder.js:671:21), <anonymous>:12:24)
    at Function.DataAccessObject.create (/projects/component-commerce/node_modules/loopback-datasource-juggler/lib/dao.js:359:13)
    at Function.replaceOrCreate (/projects/component-commerce/node_modules/loopback-datasource-juggler/lib/dao.js:924:17)
    at Promise.map (/projects/component-commerce/common/models/Model.ProductDetail.js:16:30)
    at tryCatcher (/projects/component-commerce/node_modules/bluebird/js/release/util.js:16:23)
    at MappingPromiseArray._promiseFulfilled (/projects/component-commerce/node_modules/bluebird/js/release/map.js:61:38)
    at MappingPromiseArray.PromiseArray._iterate (/projects/component-commerce/node_modules/bluebird/js/release/promise_array.js:114:31)
    at MappingPromiseArray.init (/projects/component-commerce/node_modules/bluebird/js/release/promise_array.js:78:10)
    at MappingPromiseArray._asyncInit (/projects/component-commerce/node_modules/bluebird/js/release/map.js:30:10)
```

Here's are my models:

### ProductDetail.json

```
{
  "name": "ProductDetail",
  "base": "PersistedModel",
  "indexes": {
    "unique_product_code": {
      "keys": {
        "productCode": 1,
        "venueId": 2
      }
    }
  },
  "plural": "product-detail",
  "strict": true,
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "replaceOnPUT": true,
  "properties": {
    "productName": {
      "type": "String",
      "required": true
    },
    "productDescription": {
      "type": "String"
    },
    "brand": {
      "type": "String",
      "required": true,
      "default": "Non-branded"
    },
    "attributes": {
      "type": "ProductAttribute"
    },
    "locale": {
      "type": "String",
      "required": true,
      "default": "zh"
    }
  },
  "validations": [],
  "relations": {
    "product": {
      "type": "belongsTo",
      "model": "Product",
      "foreignKey": "productId",
      "options": {
        "validate": true
      }
    }
  },
  "acls": [
    {
      "accessType": "*",
      "principalType": "ROLE",
      "principalId": "$everyone",
      "permission": "ALLOW"
    },
    {
      "accessType": "*",
      "principalType": "ROLE",
      "principalId": "$authenticated",
      "permission": "ALLOW"
    }
  ]
}
```

### ProductAttributes.json

```
{
  "name": "ProductAttribute",
  "base": "Model",
  "indexes": {},
  "strict": true,
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "properties": {
    "color": {
      "type": "String",
      "default": ""
    },
    "weight": {
      "type": "Number",
      "required": true,
      "default": 0
    },
    "weightUnit": {
      "type": "String",
      "required": true,
      "default": "grams"
    },
    "size": {
      "type": "String",
      "default": ""
    }
  },
  "validations": [],
  "relations": {}
}
```

Any help appreciated. Thanks!

**Comment by pbalan** [comment]
I think, this is not an issue. I need to define relationship like here https://loopback.io/doc/en/lb2/Embedded-models-and-relations.html#define-the-relation-in-json
